### ISSUE TITLE
Declare the dependency on php-imagick

### ISSUE THREAD

**Issue by mudrd8mz** [yedidiaklein/moodle-mod_securepdf#1]
In https://tracker.moodle.org/browse/CONTRIB-8294 @yedidiaklein says:

> Note that this plugin require installing a php extension that isn't on moodle list at all - php-imagick

For these situations, plugins should provide their own environment checking file as per https://docs.moodle.org/dev/Environment_checking - see https://tracker.moodle.org/browse/MDL-39840 for details.

**Comment by yedidiaklein** [comment]
tnx @mudrd8mz , learned the right way to declare needed php extensions...

created and declared on environment.xml.
