### ISSUE TITLE
Missing "imagic" extension

### ISSUE THREAD

**Issue by DoctorOnCall** [yedidiaklein/moodle-mod_securepdf#6]
Hi,

I have followed the instruction as below, 

    Please note that you have to install a PHP module that is not needed by Moodle itself.
    Install php-imagick module on your system.
    (debian/ubuntu) apt-get install php-imagick
    (Redhat/Centos) yum install php-imagick
    Configure imagemagick to allow PDF reading, Add <policy domain="coder" rights="read" pattern="PDF"> to the policy at /etc/ImageMagick-6/policy.xml see more details here : https://stackoverflow.com/questions/52703123/override-default-imagemagick-policy-xml
    Restart php-fpm or your web server.
    cd [moodle]/mod/
    git clone https://github.com/yedidiaklein/moodle-mod_securepdf.git securepdf
    Go to your moodle Notification Page and install. 

But still showing me imagic plugin missing as on this screenshot: https://tinyurl.com/yjoamwd4 

Could you help me to fix this issue pls?

**Comment by yedidiaklein** [comment]
What linux distro do you use ? Which web server ?
The simplest way would be to reboot your server -yhen you will be sure that everything was restarted.

Good luck

**Comment by DoctorOnCall** [comment]
Hi, it’s ubuntu 20.04 with apache2, moodle 3.11

**Comment by yedidiaklein** [comment]
You should  restart php-fpm
sudo systemctl restart php-fpm

**Comment by DoctorOnCall** [comment]
Tried but getting this - 
"
Failed to restart php-fpm.service: Unit php-fpm.service not found.
"
![image](https://user-images.githubusercontent.com/41385546/125233465-32227400-e311-11eb-9ecc-5fcc7577883a.png)

**Comment by yedidiaklein** [comment]
Could you restart the whole server ? That's the simplest way to make sure that everything restart..

**Comment by DoctorOnCall** [comment]
You mean stop instance and start again?

**Comment by yedidiaklein** [comment]
Restart the instance
